version: '3.9'

x-php-cli: &php-cli
    build:
        context: ./php_cli
        dockerfile: Dockerfile
        target: ${PHP_CLI_BUILD_TARGET:-${BUILD_TARGET?Build mode php-cli}}
    # restart: unless-stopped
    working_dir: /var/project
    volumes:
        - ../:/var/project

services:
    # Nginx Service
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ../:/var/project
        ports:
            - ${NGINX_SERVICE_PORT?Not nginx port}:80
        networks:
            - azb-network

    # PHP Service
    php-fpm:
        build:
            context: ./php
            dockerfile: Dockerfile
            target: ${PHP_FPM_BUILD_TARGET:-${BUILD_TARGET?Build mode php-fpm}}
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-php-fpm
        restart: unless-stopped
        tty: true
        volumes:
            - ../:/var/project
        ports:
            - "5173:5173"
        depends_on:
            - mysql
        networks:
            - azb-network

    # Database Service
    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-mysql
        ports:
            - ${MYSQL_SERVICE_PORT?Not mysql port}:3306
        env_file:
            -   ./mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - azb-network

    # Worker: default
    worker-default:
        <<: *php-cli
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-worker-default
        restart: unless-stopped
        depends_on:
            - php-fpm
        command: ['./artisan', 'queue:work', '--queue=default', '--sleep=4', '--tries=3']
        networks:
            - azb-network

    # Worker: avatars
    worker-avatars:
        <<: *php-cli
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-worker-avatars
        restart: unless-stopped
        depends_on:
            - php-fpm
        command: ['./artisan', 'queue:work', '--queue=avatars', '--sleep=4', '--tries=3' ]
        networks:
            - azb-network

    node:
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-node
        build:
            context: ./node
            dockerfile: Dockerfile
            target: ${FRONT_END_TARGET}
        ports:
            - 3000:3000
            # - "5173:5173"
            # - ${FRONT_END_DEVELOP_PORT}:8090
            # - ${FRONT_END_PRODUCTION_PORT}:80
        volumes:
            - ../:/var/project
        command: [ 'npm', 'run', 'dev' ]
        networks:
            - azb-network

    # Swagger Service
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-swagger-ui
        ports:
            - ${SWAGGER_SERVICE_PORT}:8080
        volumes:
            - ../docs:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/api-docs.yaml
            URLS_PRIMARY_NAME: "CheckServer"

networks:
    azb-network:
        driver: bridge